name: example-environment
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base=4.0
  - r-dplyr
  - r-ggplot2
  - r-reshape2
  - r-tidyverse
  - r-plotly
  - r-stringr
  - python=3.9
  - psutil
  - toolz
  - dill
  - partd
  - bokeh
  - dask
  - pip
  - pip:
    - plotly 
    - scikit-learn
    - pandas
    - matplotlib
    - numpy
    - seaborn
    - statsmodels
    - scipy
